/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */

import '@stencil/core';

declare global {
  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {}
  }
  namespace JSXElements {}

  interface HTMLElement {
    componentOnReady?: () => Promise<this | null>;
  }

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}
}


declare global {

  namespace StencilComponents {
    interface Warp10Download {
      'horizontal': boolean;
    }
  }

  interface HTMLWarp10DownloadElement extends StencilComponents.Warp10Download, HTMLStencilElement {}

  var HTMLWarp10DownloadElement: {
    prototype: HTMLWarp10DownloadElement;
    new (): HTMLWarp10DownloadElement;
  };
  interface HTMLElementTagNameMap {
    'warp10-download': HTMLWarp10DownloadElement;
  }
  interface ElementTagNameMap {
    'warp10-download': HTMLWarp10DownloadElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'warp10-download': JSXElements.Warp10DownloadAttributes;
    }
  }
  namespace JSXElements {
    export interface Warp10DownloadAttributes extends HTMLAttributes {
      'horizontal'?: boolean;
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }

export declare function defineCustomElements(window: any): void;